### ISSUE TITLE
Error when trying to install via the Extension Manager

### ISSUE THREAD

**Issue by Cruiser13** [pimcore-extensions/manager#1]
I installed the plugin via composer and in Pimcore admin.

I can now see a list of all available plugins at packagist but when I click the download/install button I do get the error "no composer json found".

**Comment by rafalgalka** [comment]
I think we can handle situation when there is no composer.json and show popup window with form (project name, description, author) and invoke `composer init`.

**Comment by rafalgalka** [comment]
> .. it looks like composer did not successfully run because the required version "1.0.0-alpha8" of composer was not found...

Until composer reaches stable release you need to add `"minimum-stability": "dev"` to your composer.json, as mentioned in [README](https://github.com/pimcore-extensions/manager/blob/master/README.md)

Problems related to composer.json location fixed in 7457f6b1ecdfb1915c88e576f7014ee974dd42f7
