### ISSUE TITLE
Class Packagist\Api\Client not found in .../IndexController.php on line 9

### ISSUE THREAD

**Issue by kroupa1985** [pimcore-extensions/manager#13]
Why does the extension manager throws this error when i press on the download button ?

Class 'Packagist\Api\Client' not found in <b>/var/www/rauterjevi.com/plugins/Manager/controllers/IndexController.php</b> on line <b>9</b>

**Comment by Hagith** [comment]
It's a known issue related to: https://www.pimcore.org/issues/browse/PIMCORE-2690
Before it will be fixed you can install extension manager from composer.json located in pimcore_document_root.

**Comment by kroupa1985** [comment]
It didnt work because i installed extension manager with download link here and copied it to /plugins directory. This obviusly couses this problem. Now i reinstalled it from composer and the thing works :)

**Comment by Hagith** [comment]
Just for the record, all pimcore extensions should be installed by composer. Simple copying is not enough since pimcore 3.x.
