### ISSUE TITLE
Cannot install: Symfony console versions conflict

### ISSUE THREAD

**Issue by hyrmedia** [pimcore-extensions/manager#14]
When attempting to install the package with Composer I get the following output. It does not appear that the plugin has been installed.

```
Using version ^0.1.2 for pimcore-extensions/manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: symfony/console[2.6.x-dev, v2.8.1].
    - Can only install one of: symfony/console[v2.8.1, 2.6.x-dev].
    - Can only install one of: symfony/console[2.6.x-dev, v2.8.1].
    - pimcore-extensions/manager 0.1.2 requires symfony/console ~2.6.0 -> satisfiable by symfony/console[2.6.x-dev]
.
    - Installation request for pimcore-extensions/manager ^0.1.2 -> satisfiable by pimcore-extensions/manager[0.1.2
].
    - Installation request for symfony/console == 2.8.1.0 -> satisfiable by symfony/console[v2.8.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by josh-palan** [comment]
Bump. Having the same issue:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: symfony/console[2.6.x-dev, v3.1.2].
    - Can only install one of: symfony/console[v3.1.2, 2.6.x-dev].
    - Can only install one of: symfony/console[2.6.x-dev, v3.1.2].
    - pimcore-extensions/manager 0.1.2 requires symfony/console ~2.6.0 -> satisfiable by symfony/console[2.6.x-dev].
    - Installation request for pimcore-extensions/manager ^0.1.2 -> satisfiable by pimcore-extensions/manager[0.1.2].
    - Installation request for symfony/console (locked at v3.1.2, required as ~3) -> satisfiable by symfony/console[v3.1.2].

**Comment by Hagith** [comment]
Will look into this. 
Just to be sure, issue occurs with the latest pimcore version 4.1.3?

**Comment by josh-palan** [comment]
Correct. Version 4.1.3, revision 3858

**Comment by Hagith** [comment]
Just pushed 0.2.0 release which should work properly with latest pimcore version. 
Please check README as it's updated and there are some important notes about using manager.
